<a href="https://colab.research.google.com/github/manish-gitx/ml_assignment/blob/main/ola_case_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ola case study

## Importing the Dependency

In [ ]:
import numpy as np
import pandas as pd
import gdown

## Importing the Dataset

In [ ]:
file_id = "16g-OJ_4GnG0P8FEFgTa50RMubVSBvIZl"
output_file = "ola_case_study.csv"

# Download the CSV file from Google Drive
gdown.download(id=file_id, output=output_file, quiet=False)

# Load the data into a Pandas DataFrame without specifying an index column
df = pd.read_csv(output_file)

Downloading...
From: https://drive.google.com/uc?id=16g-OJ_4GnG0P8FEFgTa50RMubVSBvIZl
To: /content/ola_case_study.csv
100%|██████████| 1.13M/1.13M [00:00<00:00, 84.7MB/s]

In [ ]:
df.head()

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,Unnamed: 0,MMM-YY,Driver_ID,Age,Gender,City,Education_Level,Income,Dateofjoining,LastWorkingDate,Joining Designation,Grade,Total Business Value,Quarterly Rating
0,0,01/01/19,1,28.0,0.0,C23,2,57387,24/12/18,NaN,1,1,2381060,2
1,1,02/01/19,1,28.0,0.0,C23,2,57387,24/12/18,NaN,1,1,-665480,2
2,2,03/01/19,1,28.0,0.0,C23,2,57387,24/12/18,03/11/19,1,1,0,2
3,3,11/01/20,2,31.0,0.0,C7,2,67016,11/06/20,NaN,2,2,0,1
4,4,12/01/20,2,31.0,0.0,C7,2,67016,11/06/20,NaN,2,2,0,1

## Analysis of the dataset

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19104 entries, 0 to 19103
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            19104 non-null  int64
 1   MMM-YY                19104 non-null  object
 2   Driver_ID             19104 non-null  int64
 3   Age                   19043 non-null  float64
 4   Gender                19052 non-null  float64
 5   City                  19104 non-null  object
 6   Education_Level       19104 non-null  int64
 7   Income                19104 non-null  int64
 8   Dateofjoining         19104 non-null  object
 9   LastWorkingDate       1616 non-null   object
 10  Joining Designation   19104 non-null  int64
 11  Grade                 19104 non-null  int64
 12  Total Business Value  19104 non-null  int64
 13  Quarterly Rating      19104 non-null  int64
dtypes: float64(2), int64(8), object(4)
memory usage: 2.0+ MB

### Converting object types into datetime type

In [ ]:
df['MMM-YY'] = pd.to_datetime(df['MMM-YY'])
df['LastWorkingDate'] = pd.to_datetime(df['LastWorkingDate'])
df['Dateofjoining'] = pd.to_datetime(df['Dateofjoining'])

<ipython-input-43-d55a7f879108>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['MMM-YY'] = pd.to_datetime(df['MMM-YY'])
<ipython-input-43-d55a7f879108>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['LastWorkingDate'] = pd.to_datetime(df['LastWorkingDate'])
<ipython-input-43-d55a7f879108>:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dateofjoining'] = pd.to_datetime(df['Dateofjoining'])

## Separating the numerical datatype columns from the dataset

we are droping `Driver_ID` from the dataset

In [ ]:
df_num = df.drop(columns='Driver_ID')

In [ ]:
df_num.head()

,Unnamed: 0,MMM-YY,Age,Gender,City,Education_Level,Income,Dateofjoining,LastWorkingDate,Joining Designation,Grade,Total Business Value,Quarterly Rating
0,0,2019-01-01,28.0,0.0,C23,2,57387,2018-12-24,NaT,1,1,2381060,2
1,1,2019-02-01,28.0,0.0,C23,2,57387,2018-12-24,NaT,1,1,-665480,2
2,2,2019-03-01,28.0,0.0,C23,2,57387,2018-12-24,2019-03-11,1,1,0,2
3,3,2020-11-01,31.0,0.0,C7,2,67016,2020-11-06,NaT,2,2,0,1
4,4,2020-12-01,31.0,0.0,C7,2,67016,2020-11-06,NaT,2,2,0,1

Getting the numeric type coulumns and storing it in `num_cols`

In [ ]:
num_cols = df_num.select_dtypes(np.number)

In [ ]:
df_num.isnull().sum()

Unnamed: 0                  0
MMM-YY                      0
Age                        61
Gender                     52
City                        0
Education_Level             0
Income                      0
Dateofjoining               0
LastWorkingDate         17488
Joining Designation         0
Grade                       0
Total Business Value        0
Quarterly Rating            0
dtype: int64

We got to know that the columns `Age` and `Gender` have some missing values. We don't need to care about the misssing values in `LastWorkingDate`

In [ ]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5, weights='uniform')
imputer.fit(num_cols)
df_new = imputer.transform(num_cols)

In [ ]:
df_new

array([[ 0.00000e+00,  2.80000e+01,  0.00000e+00, ...,  1.00000e+00,
         2.38106e+06,  2.00000e+00],
       [ 1.00000e+00,  2.80000e+01,  0.00000e+00, ...,  1.00000e+00,
        -6.65480e+05,  2.00000e+00],
       [ 2.00000e+00,  2.80000e+01,  0.00000e+00, ...,  1.00000e+00,
         0.00000e+00,  2.00000e+00],
       ...,
       [ 1.91010e+04,  3.00000e+01,  0.00000e+00, ...,  2.00000e+00,
         0.00000e+00,  2.00000e+00],
       [ 1.91020e+04,  3.00000e+01,  0.00000e+00, ...,  2.00000e+00,
         2.00420e+05,  2.00000e+00],
       [ 1.91030e+04,  3.00000e+01,  0.00000e+00, ...,  2.00000e+00,
         4.11480e+05,  2.00000e+00]])

`cols` stores the column names of numerical datatype

In [ ]:
cols = num_cols.columns
cols

Index(['Unnamed: 0', 'Age', 'Gender', 'Education_Level', 'Income',
       'Joining Designation', 'Grade', 'Total Business Value',
       'Quarterly Rating'],
      dtype='object')

In [ ]:
df_num = pd.DataFrame(df_new, columns=cols)

In [ ]:
df_num.head()

,Unnamed: 0,Age,Gender,Education_Level,Income,Joining Designation,Grade,Total Business Value,Quarterly Rating
0,0.0,28.0,0.0,2.0,57387.0,1.0,1.0,2381060.0,2.0
1,1.0,28.0,0.0,2.0,57387.0,1.0,1.0,-665480.0,2.0
2,2.0,28.0,0.0,2.0,57387.0,1.0,1.0,0.0,2.0
3,3.0,31.0,0.0,2.0,67016.0,2.0,2.0,0.0,1.0
4,4.0,31.0,0.0,2.0,67016.0,2.0,2.0,0.0,1.0

In [ ]:
df_num.isnull().sum()

Unnamed: 0              0
Age                     0
Gender                  0
Education_Level         0
Income                  0
Joining Designation     0
Grade                   0
Total Business Value    0
Quarterly Rating        0
dtype: int64

## Concatinating numerical datatype and categorical datatype columns

In [ ]:
set(df.columns)

{'Age',
 'City',
 'Dateofjoining',
 'Driver_ID',
 'Education_Level',
 'Gender',
 'Grade',
 'Income',
 'Joining Designation',
 'LastWorkingDate',
 'MMM-YY',
 'Quarterly Rating',
 'Total Business Value',
 'Unnamed: 0'}

In [ ]:
set(df_num.columns)

{'Age',
 'Education_Level',
 'Gender',
 'Grade',
 'Income',
 'Joining Designation',
 'Quarterly Rating',
 'Total Business Value',
 'Unnamed: 0'}

In [ ]:
leftover = set(df.columns).difference(set(df_num.columns))

In [ ]:
leftover

{'City', 'Dateofjoining', 'Driver_ID', 'LastWorkingDate', 'MMM-YY'}

In [ ]:
leftover = list(leftover)

In [ ]:
df_con =  pd.concat([df_num, df[leftover]], axis=1)
df_con['Driver_ID'] = df['Driver_ID']

In [ ]:
df_con.head()

,Unnamed: 0,Age,Gender,Education_Level,Income,Joining Designation,Grade,Total Business Value,Quarterly Rating,Dateofjoining,MMM-YY,LastWorkingDate,City,Driver_ID
0,0.0,28.0,0.0,2.0,57387.0,1.0,1.0,2381060.0,2.0,2018-12-24,2019-01-01,NaT,C23,1
1,1.0,28.0,0.0,2.0,57387.0,1.0,1.0,-665480.0,2.0,2018-12-24,2019-02-01,NaT,C23,1
2,2.0,28.0,0.0,2.0,57387.0,1.0,1.0,0.0,2.0,2018-12-24,2019-03-01,2019-03-11,C23,1
3,3.0,31.0,0.0,2.0,67016.0,2.0,2.0,0.0,1.0,2020-11-06,2020-11-01,NaT,C7,2
4,4.0,31.0,0.0,2.0,67016.0,2.0,2.0,0.0,1.0,2020-11-06,2020-12-01,NaT,C7,2

In [ ]:
df_con.isnull().sum()

Unnamed: 0                  0
Age                         0
Gender                      0
Education_Level             0
Income                      0
Joining Designation         0
Grade                       0
Total Business Value        0
Quarterly Rating            0
Dateofjoining               0
MMM-YY                      0
LastWorkingDate         17488
City                        0
Driver_ID                   0
dtype: int64

In [ ]:
columns = {
    "MMM-YY" : "last",
    "Age" : "last",
    "Gender" : "last",
    "City" : "last",
    "Education_Level" : 'last',
    "Income" : "last",
    "Dateofjoining" : "last",
    "LastWorkingDate" : "last",
    "Joining Designation" : "last",
    "Grade" : "last",
    "Total Business Value" : "sum",
    "Quarterly Rating" : "last",
}

df_agg = df_con.groupby('Driver_ID').agg(columns)
df_agg = df_agg.reset_index()

In [ ]:
qrf = df_con.groupby('Driver_ID').agg({"Quarterly Rating" : "first"}).reset_index()
qrl = df_con.groupby('Driver_ID').agg({"Quarterly Rating" : "last"}).reset_index()

In [ ]:
qrf

      Driver_ID  Quarterly Rating
0             1               2.0
1             2               1.0
2             4               1.0
3             5               1.0
4             6               1.0
...         ...               ...
2376       2784               3.0
2377       2785               1.0
2378       2786               2.0
2379       2787               2.0
2380       2788               1.0

[2381 rows x 2 columns]

In [ ]:
qrl

      Driver_ID  Quarterly Rating
0             1               2.0
1             2               1.0
2             4               1.0
3             5               1.0
4             6               2.0
...         ...               ...
2376       2784               4.0
2377       2785               1.0
2378       2786               1.0
2379       2787               1.0
2380       2788               2.0

[2381 rows x 2 columns]

In [ ]:
qri = qrf.merge(qrl, how='inner', on='Driver_ID')

In [ ]:
qri.head()

   Driver_ID  Quarterly Rating_x  Quarterly Rating_y
0          1                 2.0                 2.0
1          2                 1.0                 1.0
2          4                 1.0                 1.0
3          5                 1.0                 1.0
4          6                 1.0                 2.0

In [ ]:
qri['increase'] = qri['Quarterly Rating_y'] - qri['Quarterly Rating_x']

In [ ]:
qri.head()

   Driver_ID  Quarterly Rating_x  Quarterly Rating_y  increase
0          1                 2.0                 2.0       0.0
1          2                 1.0                 1.0       0.0
2          4                 1.0                 1.0       0.0
3          5                 1.0                 1.0       0.0
4          6                 1.0                 2.0       1.0

In [ ]:
df_con = df_con.merge(qri[['Driver_ID', 'increase']], how='left', on='Driver_ID')

In [ ]:
df_con.head()

,Unnamed: 0,Age,Gender,Education_Level,Income,Joining Designation,Grade,Total Business Value,Quarterly Rating,Dateofjoining,MMM-YY,LastWorkingDate,City,Driver_ID,increase
0,0.0,28.0,0.0,2.0,57387.0,1.0,1.0,2381060.0,2.0,2018-12-24,2019-01-01,NaT,C23,1,0.0
1,1.0,28.0,0.0,2.0,57387.0,1.0,1.0,-665480.0,2.0,2018-12-24,2019-02-01,NaT,C23,1,0.0
2,2.0,28.0,0.0,2.0,57387.0,1.0,1.0,0.0,2.0,2018-12-24,2019-03-01,2019-03-11,C23,1,0.0
3,3.0,31.0,0.0,2.0,67016.0,2.0,2.0,0.0,1.0,2020-11-06,2020-11-01,NaT,C7,2,0.0
4,4.0,31.0,0.0,2.0,67016.0,2.0,2.0,0.0,1.0,2020-11-06,2020-12-01,NaT,C7,2,0.0

In [ ]:
qrf = df_con.groupby('Driver_ID').agg({"Income" : "first"}).reset_index()
qrl = df_con.groupby('Driver_ID').agg({"Income" : "last"}).reset_index()
qri = qrf.merge(qrl, how='inner', on='Driver_ID')

In [ ]:
qri.head()

   Driver_ID  Income_x  Income_y
0          1   57387.0   57387.0
1          2   67016.0   67016.0
2          4   65603.0   65603.0
3          5   46368.0   46368.0
4          6   78728.0   78728.0

In [ ]:
qri.loc[qri['Income_x'] < qri['Income_y'], 'income_increase'] = 1
qri.loc[qri['Income_x'] >= qri['Income_y'], 'income_increase'] = 0

In [ ]:
qri.head()

   Driver_ID  Income_x  Income_y  income_increase
0          1   57387.0   57387.0              0.0
1          2   67016.0   67016.0              0.0
2          4   65603.0   65603.0              0.0
3          5   46368.0   46368.0              0.0
4          6   78728.0   78728.0              0.0

In [ ]:
df_con = df_con.merge(qri[['Driver_ID', 'income_increase']], how='left', on='Driver_ID')

In [ ]:
df_con.head()

,Unnamed: 0,Age,Gender,Education_Level,Income,Joining Designation,Grade,Total Business Value,Quarterly Rating,Dateofjoining,MMM-YY,LastWorkingDate,City,Driver_ID,increase,income_increase
0,0.0,28.0,0.0,2.0,57387.0,1.0,1.0,2381060.0,2.0,2018-12-24,2019-01-01,NaT,C23,1,0.0,0.0
1,1.0,28.0,0.0,2.0,57387.0,1.0,1.0,-665480.0,2.0,2018-12-24,2019-02-01,NaT,C23,1,0.0,0.0
2,2.0,28.0,0.0,2.0,57387.0,1.0,1.0,0.0,2.0,2018-12-24,2019-03-01,2019-03-11,C23,1,0.0,0.0
3,3.0,31.0,0.0,2.0,67016.0,2.0,2.0,0.0,1.0,2020-11-06,2020-11-01,NaT,C7,2,0.0,0.0
4,4.0,31.0,0.0,2.0,67016.0,2.0,2.0,0.0,1.0,2020-11-06,2020-12-01,NaT,C7,2,0.0,0.0

In [ ]:
df_con.loc[df_con['LastWorkingDate'].isna(), 'Churn']=0

In [ ]:
df_con.head()

,Unnamed: 0,Age,Gender,Education_Level,Income,Joining Designation,Grade,Total Business Value,Quarterly Rating,Dateofjoining,MMM-YY,LastWorkingDate,City,Driver_ID,increase,income_increase,Churn
0,0.0,28.0,0.0,2.0,57387.0,1.0,1.0,2381060.0,2.0,2018-12-24,2019-01-01,NaT,C23,1,0.0,0.0,0.0
1,1.0,28.0,0.0,2.0,57387.0,1.0,1.0,-665480.0,2.0,2018-12-24,2019-02-01,NaT,C23,1,0.0,0.0,0.0
2,2.0,28.0,0.0,2.0,57387.0,1.0,1.0,0.0,2.0,2018-12-24,2019-03-01,2019-03-11,C23,1,0.0,0.0,NaN
3,3.0,31.0,0.0,2.0,67016.0,2.0,2.0,0.0,1.0,2020-11-06,2020-11-01,NaT,C7,2,0.0,0.0,0.0
4,4.0,31.0,0.0,2.0,67016.0,2.0,2.0,0.0,1.0,2020-11-06,2020-12-01,NaT,C7,2,0.0,0.0,0.0

In [ ]:
df_con.loc[df_con['Churn'].isna(), 'Churn'] = 1

In [ ]:
df_con.head()

,Unnamed: 0,Age,Gender,Education_Level,Income,Joining Designation,Grade,Total Business Value,Quarterly Rating,Dateofjoining,MMM-YY,LastWorkingDate,City,Driver_ID,increase,income_increase,Churn
0,0.0,28.0,0.0,2.0,57387.0,1.0,1.0,2381060.0,2.0,2018-12-24,2019-01-01,NaT,C23,1,0.0,0.0,0.0
1,1.0,28.0,0.0,2.0,57387.0,1.0,1.0,-665480.0,2.0,2018-12-24,2019-02-01,NaT,C23,1,0.0,0.0,0.0
2,2.0,28.0,0.0,2.0,57387.0,1.0,1.0,0.0,2.0,2018-12-24,2019-03-01,2019-03-11,C23,1,0.0,0.0,1.0
3,3.0,31.0,0.0,2.0,67016.0,2.0,2.0,0.0,1.0,2020-11-06,2020-11-01,NaT,C7,2,0.0,0.0,0.0
4,4.0,31.0,0.0,2.0,67016.0,2.0,2.0,0.0,1.0,2020-11-06,2020-12-01,NaT,C7,2,0.0,0.0,0.0

In [ ]:
df_con.describe()

,Unnamed: 0,Age,Gender,Education_Level,Income,Joining Designation,Grade,Total Business Value,Quarterly Rating,Dateofjoining,MMM-YY,LastWorkingDate,Driver_ID,increase,income_increase,Churn
count,19104.000000,19104.000000,19104.000000,19104.000000,19104.000000,19104.000000,19104.000000,1.910400e+04,19104.000000,19104,19104,1616,19104.000000,19104.000000,19104.000000,19104.000000
mean,9551.500000,34.662353,0.418677,1.021671,65652.025126,1.690536,2.252670,5.716621e+05,2.008899,2018-04-28 20:52:54.874371840,2019-12-11 02:09:29.849246464,2019-12-21 20:59:06.534653696,1415.591133,-0.090295,0.051089,0.084590
min,0.000000,21.000000,0.000000,0.000000,10747.000000,1.000000,1.000000,-6.000000e+06,1.000000,2013-04-01 00:00:00,2019-01-01 00:00:00,2018-12-31 00:00:00,1.000000,-3.000000,0.000000,0.000000
25%,4775.750000,30.000000,0.000000,0.000000,42383.000000,1.000000,1.000000,0.000000e+00,1.000000,2016-11-29 12:00:00,2019-06-01 00:00:00,2019-06-06 00:00:00,710.000000,-1.000000,0.000000,0.000000
50%,9551.500000,34.000000,0.000000,1.000000,60087.000000,1.000000,2.000000,2.500000e+05,2.000000,2018-09-12 00:00:00,2019-12-01 00:00:00,2019-12-20 12:00:00,1417.000000,0.000000,0.000000,0.000000
75%,14327.250000,39.000000,1.000000,2.000000,83969.000000,2.000000,3.000000,6.997000e+05,3.000000,2019-11-05 00:00:00,2020-07-01 00:00:00,2020-07-03 00:00:00,2137.000000,0.000000,0.000000,0.000000
max,19103.000000,58.000000,1.000000,2.000000,188418.000000,5.000000,5.000000,3.374772e+07,4.000000,2020-12-28 00:00:00,2020-12-01 00:00:00,2020-12-28 00:00:00,2788.000000,3.000000,1.000000,1.000000
std,5514.994107,6.253090,0.492935,0.800167,30914.515344,0.836984,1.026512,1.128312e+06,1.009832,NaN,NaN,NaN,810.705321,1.169265,0.220185,0.278277

## Dropping `Income` and `Quarterly Rating` from the dataset

In [ ]:
df_con = df_con.drop(columns=['Income', 'Quarterly Rating'])

In [ ]:
df_con.head()

,Unnamed: 0,Age,Gender,Education_Level,Joining Designation,Grade,Total Business Value,Dateofjoining,MMM-YY,LastWorkingDate,City,Driver_ID,increase,income_increase,Churn
0,0.0,28.0,0.0,2.0,1.0,1.0,2381060.0,2018-12-24,2019-01-01,NaT,C23,1,0.0,0.0,0.0
1,1.0,28.0,0.0,2.0,1.0,1.0,-665480.0,2018-12-24,2019-02-01,NaT,C23,1,0.0,0.0,0.0
2,2.0,28.0,0.0,2.0,1.0,1.0,0.0,2018-12-24,2019-03-01,2019-03-11,C23,1,0.0,0.0,1.0
3,3.0,31.0,0.0,2.0,2.0,2.0,0.0,2020-11-06,2020-11-01,NaT,C7,2,0.0,0.0,0.0
4,4.0,31.0,0.0,2.0,2.0,2.0,0.0,2020-11-06,2020-12-01,NaT,C7,2,0.0,0.0,0.0

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encode = LabelEncoder()

df_con['City'] = df_con[["City"]].apply(label_encode.fit_transform)

In [ ]:
df_con.head()

,Unnamed: 0,Age,Gender,Education_Level,Joining Designation,Grade,Total Business Value,Dateofjoining,MMM-YY,LastWorkingDate,City,Driver_ID,increase,income_increase,Churn
0,0.0,28.0,0.0,2.0,1.0,1.0,2381060.0,2018-12-24,2019-01-01,NaT,15,1,0.0,0.0,0.0
1,1.0,28.0,0.0,2.0,1.0,1.0,-665480.0,2018-12-24,2019-02-01,NaT,15,1,0.0,0.0,0.0
2,2.0,28.0,0.0,2.0,1.0,1.0,0.0,2018-12-24,2019-03-01,2019-03-11,15,1,0.0,0.0,1.0
3,3.0,31.0,0.0,2.0,2.0,2.0,0.0,2020-11-06,2020-11-01,NaT,26,2,0.0,0.0,0.0
4,4.0,31.0,0.0,2.0,2.0,2.0,0.0,2020-11-06,2020-12-01,NaT,26,2,0.0,0.0,0.0

## Model Building

### Spliting features (X) and target (y)

In [ ]:
X = df_con.drop(columns=['Churn', 'Dateofjoining', 'LastWorkingDate', 'MMM-YY'] ,axis=1)
y = df_con['Churn']

### Spliting dataset into Testing and Training dataset

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score, roc_curve
from sklearn.model_selection import GridSearchCV

In [ ]:
def tune_and_evaluate_model(model, param_grid):
    grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='roc_auc')
    grid_search.fit(X_train, y_train)
    best_model = grid_search.best_estimator_
    y_pred_proba = best_model.predict_proba(X_test)[:, 1]
    accuracy = accuracy_score(y_test, best_model.predict(X_test))
    print("Best Hyperparameters:", grid_search.best_params_)
    print("Accuracy:", accuracy)
    print("Classification Report:\n", classification_report(y_test, best_model.predict(X_test)))
    roc_auc = roc_auc_score(y_test, y_pred_proba)
    fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)
    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, label=f'ROC curve (AUC = {roc_auc:.2f})')
    plt.plot([0, 1], [0, 1], 'k--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC AUC Curve')
    plt.legend(loc='lower right')
    plt.show()
    return best_model

### Random Forest (Bagging)

In [ ]:
rf_model = RandomForestClassifier(random_state=42)
rf_param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10]
}

best_rf_model = tune_and_evaluate_model(rf_model, rf_param_grid)

### AdaBoost (Boosting)

In [ ]:
ab_model = AdaBoostClassifier(random_state=42)
ab_param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 1]
}

best_ab_model = tune_and_evaluate_model(ab_model, ab_param_grid)